In [6]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(42)

In [3]:
age=np.random.uniform(25,70,12).round(0)

In [4]:
true_income=((age*1200)+np.random.normal(0,15000,12)).round(0)

In [7]:
df=pd.DataFrame({'Age':age,'Income':true_income})

In [8]:
df

     Age   Income
0   42.0  43358.0
1   68.0  89738.0
2   58.0  62649.0
3   52.0  55414.0
4   32.0  42029.0
5   32.0   9701.0
6   28.0   7726.0
7   64.0  68366.0
8   52.0  47208.0
9   57.0  73114.0
10  26.0  17580.0
11  69.0  61615.0

In [11]:
df.loc[df.Income>85000,'Income'] =np.nan

In [12]:
df

     Age   Income
0   42.0  43358.0
1   68.0      NaN
2   58.0  62649.0
3   52.0  55414.0
4   32.0  42029.0
5   32.0   9701.0
6   28.0   7726.0
7   64.0  68366.0
8   52.0  47208.0
9   57.0  73114.0
10  26.0  17580.0
11  69.0  61615.0

In [13]:
#Original data set with MNAR problem

In [14]:
#Applying shadow imputer method

In [16]:
from sklearn.impute import SimpleImputer

In [18]:
simple_imputer =SimpleImputer(strategy='mean', add_indicator=True)

In [19]:
imputed_arr=simple_imputer.fit_transform(df)

In [20]:
df_shadow=pd.DataFrame(imputed_arr, columns=['Age','Income','Missing_income_flag'])

In [21]:
df_shadow

     Age        Income  Missing_income_flag
0   42.0  43358.000000                  0.0
1   68.0  44432.727273                  1.0
2   58.0  62649.000000                  0.0
3   52.0  55414.000000                  0.0
4   32.0  42029.000000                  0.0
5   32.0   9701.000000                  0.0
6   28.0   7726.000000                  0.0
7   64.0  68366.000000                  0.0
8   52.0  47208.000000                  0.0
9   57.0  73114.000000                  0.0
10  26.0  17580.000000                  0.0
11  69.0  61615.000000                  0.0